apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat-server
        image: nowzarifarhad/fdn-chat-server:raspi1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "800m"
        ports:
        - containerPort: 9000
      nodeSelector:
        node-role.kubernetes.io/worker: 'worker'
---
apiVersion: v1
kind: Service
metadata:
  name: chat-server-service
spec:
  selector:
    app: chat-server
  ports:
  - name: "chat-server-random"
    port: 9000
    targetPort: 9000